### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by FogLizard** [bartoszek/AUR-blender-git#3]
FAILED: intern/cycles/kernel/shaders/node_math.oso 

/opt/osl/bin/oslc: error while loading shared libraries: libOpenEXR-3_0.so.27: cannot open shared object file: No such file or directory

It's been updated to usr/lib/libOpenEXR-3_0.so.28

ls -lart /usr/lib | grep EXR
lrwxrwxrwx   1 root root        21 May 19 09:24 libOpenEXRUtil.so -> libOpenEXRUtil-3_0.so
-rwxr-xr-x   1 root root    198496 May 19 09:24 libOpenEXRUtil-3_0.so.28.0.0
lrwxrwxrwx   1 root root        28 May 19 09:24 libOpenEXRUtil-3_0.so.28 -> libOpenEXRUtil-3_0.so.28.0.0
lrwxrwxrwx   1 root root        24 May 19 09:24 libOpenEXRUtil-3_0.so -> libOpenEXRUtil-3_0.so.28
lrwxrwxrwx   1 root root        17 May 19 09:24 libOpenEXR.so -> libOpenEXR-3_0.so
-rwxr-xr-x   1 root root   3176400 May 19 09:24 libOpenEXR-3_0.so.28.0.0
lrwxrwxrwx   1 root root        24 May 19 09:24 libOpenEXR-3_0.so.28 -> libOpenEXR-3_0.so.28.0.0
lrwxrwxrwx   1 root root        20 May 19 09:24 libOpenEXR-3_0.so -> libOpenEXR-3_0.so.28

**Comment by FogLizard** [comment]
if openexr is rolled back to openexr-3.0.1-2, it fails on imath

/opt/osl/bin/oslc: error while loading shared libraries: libImath-3_0.so.27: cannot open shared object file: No such file or directory

**Comment by bartoszek** [comment]
Please rebuild `opencolorio-qfix` `openimageio-qfix` and `openshadinglanguage-qfix` 

To mitigate such issues please use [rebuild-detector](https://aur.archlinux.org/packages/rebuild-detector]

**Comment by FogLizard** [comment]
Thank you, I've done that, now it keeps failing with a different error. I've rebuilt alembic-qfix

[319/4635] Building CXX object intern/cycles/render/CMakeFiles/cycles_render.dir/alembic_read.cpp.o
FAILED: intern/cycles/render/CMakeFiles/cycles_render.dir/alembic_read.cpp.o 
/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_LOCALE_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DBOOST_WAVE_DYN_LINK -DCCL_NAMESPACE_BEGIN="namespace ccl {" -DCCL_NAMESPACE_END=} -DCYCLES_GFLAGS_NAMESPACE=gflags -DEMBREE_STATIC_LIB -DGLEW_NO_GLU -DGOOGLE_GLOG_DLL_DECL="" -DNDEBUG -DOSL_STATIC_BUILD -DOSL_STATIC_LIBRARY -DTBB_SUPPRESS_DEPRECATED_MESSAGES=1 -DWITH_ALEMBIC -DWITH_BLENDER_GUARDEDALLOC -DWITH_CYCLES_LOGGING -DWITH_EMBREE -DWITH_GL_PROFILE_CORE -DWITH_KERNEL_AVX -DWITH_KERNEL_AVX2 -DWITH_KERNEL_SSE2 -DWITH_KERNEL_SSE3 -DWITH_KERNEL_SSE41 -DWITH_OCIO -DWITH_OPENGL -DWITH_OPENSUBDIV -DWITH_OPENVDB -DWITH_OPENVDB_BLOSC -DWITH_OSL -DWITH_SYSTEM_PUGIXML -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D__LITTLE_ENDIAN__ -D__MMX__ -D__SSE2__ -D__SSE__ -I/home/pink/.cache/pikaur/build/blender-git/src/blender/intern/cycles/../atomic -I/home/pink/.cache/pikaur/build/blender-git/src/blender/intern/cycles/render/.. -I/home/pink/.cache/pikaur/build/blender-git/src/blender/intern/cycles/render/../../glew-mx -I/home/pink/.cache/pikaur/build/blender-git/src/blender/intern/cycles/render/../../sky/include -isystem /opt/osl/include -isystem /home/pink/.cache/pikaur/build/blender-git/src/blender/extern/glog/include -isystem /home/pink/.cache/pikaur/build/blender-git/src/blender/extern/gflags/src -isystem /opt/oiio/include -isystem /opt/oiio/include/OpenImageIO -isystem /usr/include/OpenEXR -isystem /usr/include/Imath -isystem /opt/ocio/include -Wuninitialized -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wno-suggest-override -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5 -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fuse-ld=gold -fopenmp -std=c++17 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing  -msse2 -fmacro-prefix-map="/home/pink/.cache/pikaur/build/blender-git/src/blender/"="" -fmacro-prefix-map="/home/pink/.cache/pikaur/build/blender-git/src/build/"="" -fno-trapping-math -fno-math-errno -fno-signed-zeros -fno-signaling-nans -fno-rounding-math -mfpmath=sse -Werror=float-conversion -Werror=double-promotion -Wno-error=unused-macros -Wno-maybe-uninitialized -O2 -DNDEBUG -MD -MT intern/cycles/render/CMakeFiles/cycles_render.dir/alembic_read.cpp.o -MF intern/cycles/render/CMakeFiles/cycles_render.dir/alembic_read.cpp.o.d -o intern/cycles/render/CMakeFiles/cycles_render.dir/alembic_read.cpp.o -c /home/pink/.cache/pikaur/build/blender-git/src/blender/intern/cycles/render/alembic_read.cpp
/home/pink/.cache/pikaur/build/blender-git/src/blender/intern/cycles/render/alembic_read.cpp:609:41: internal compiler error: in build_target_expr_with_type, at cp/tree.c:845
  609 |   static constexpr TypeDesc type_desc = TypeFloat;
      |                                         ^~~~~~~~~
0x1797368 internal_error(char const*, ...)
        ???:0
0x67f8f9 fancy_abort(char const*, int, char const*)
        ???:0
0x850ba4 store_init_value(tree_node*, tree_node*, vec<tree_node*, va_gc, vl_embed>**, int)
        ???:0
0x70773d cp_finish_decl(tree_node*, tree_node*, bool, tree_node*, int)
        ???:0
0x7128bc grokfield(cp_declarator const*, cp_decl_specifier_seq*, tree_node*, bool, tree_node*, tree_node*)
        ???:0
0x7ce2fe c_parse_file()
        ???:0
0x8a252d c_common_parse_file()
        ???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.archlinux.org/> for instructions.
[334/4635] Building CXX object intern/cycles/kernel/CMakeFiles/cycles_kernel.dir/kernels/cpu/kernel.cpp.o
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by FogLizard** [comment]
I don't know what has changed, but I didn't do anything else and I've just been able to build (with a couple of warnings and redownloading the sources) after clearing pikaur cache and it works.
I guess this issue is resolved, thanks.

**Comment by bartoszek** [comment]
This is a known regression in `gcc:11` you can stumble upon this issue also in other packages until the upstream patch gets applied to the Arch `gcc` package.

https://bugs.archlinux.org/task/70930

**Comment by rhysday** [comment]
Is this the CMake error when trying to compile from the AUR?

**Comment by bartoszek** [comment]
Nope, this was dependency and GCC regression problem, but was solved with never version of GCC/blender.

**Comment by rhysday** [comment]
Still getting CMake error, should I install gcc-git from the AUR? I attempted to but it was taking forever to compile.

**Comment by bartoszek** [comment]
Could you perhaps show me error messages you're getting?

**Comment by rhysday** [comment]
>==> python version detected: 3.9
>loading initial cache file /home/me/.local/cache/yay/blender-git/src/blender/build_files/cmake/config/blender_release.cmake
>CMake Error: The source directory "/home/me/.local/cache/yay/blender-git/src" does not appear to contain CMakeLists.txt.
>Specify --help for usage, or press the help button on the CMake GUI.
>==> ERROR: A failure occurred in build().

**Comment by bartoszek** [comment]
This is the `yay` specific issue: check #4
